version: "3.3"
services:
  tfm-backend:
    build: .
    restart: always
    image: tfm-backend
    ports: ["9000:9000"]
    container_name: tfm-backend
    depends_on: [tfm-database]

  tfm-database:
    restart: always
    ports: ["5432:5432"]
    image: postgres:14.2-alpine
    container_name: tfm-database
    env_file:
      - .env.docker
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/:rw
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf